name: Deploy Budget Service Go

on:
  push:
    branches:
      - main

jobs:
  deploy-budget-service-go:
    name: Deploy Budget Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Get Short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
        shell: bash
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build Binary
        run: |
          cd apps/budget-service && go build -o bin/cmd main.go && zip main.zip bin/cmd

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.HACKATHON_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.HACKATHON_AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: budget-service-go
          zip_file: apps/budget-service/main.zip
          handler: bin/cmd
